steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/dockerweb:$COMMIT_SHA',
      '-f', 'simple-web/Dockerfile',
      'simple-web'
    ]

images:
  - 'gcr.io/$PROJECT_ID/dockerweb:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
